server:
  port: 0

spring:
  application:
    name: vedio-funny-model
  
  # 引入公共配置（超简单方式）
  config:
    import:
      - "classpath:application-common.yml"
      - "optional:nacos:vedio-funny-common.yml?group=DEFAULT_GROUP&refreshEnabled=true"
  
  # 服务特定元数据
  cloud:
    nacos:
      discovery:
        metadata:
          description: VedioFun模型服务 - AI模型管理与推理

# 模型服务特定配置
model:
  # 模型存储路径
  storage-path: ./models
  # 最大模型文件大小 (MB)
  max-file-size: 1024
  # 支持的模型格式
  supported-formats:
    - "*.onnx"
    - "*.pt"
    - "*.pth"
    - "*.pb"

# 日志配置 (生产模式)
logging:
  level:
    root: INFO
    com.vediofun.model: INFO
    org.springframework.web: WARN
    org.springframework.cloud.context: WARN
    com.alibaba.nacos: WARN 

tencent:
  cos:
    secret-id: 1254322764
    secret-key: AKIDBF9sRo9LLCqKjwwiJivxoTxGMEsJYcS5
    bucket-name: vedio-funny-1254322764
    region: ap-guangzhou
    base-url: https://vedio-funny-1254322764.cos.ap-guangzhou.myqcloud.com/ 